---
title: "Sentiment Analysis"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
library("tm")
library("SnowballC")
library("wordcloud")
library("RColorBrewer")
library("syuzhet")
library("ggplot2")


```



```{r}
text <- readLines("glassdoortest.csv")

TextDoc <- Corpus(VectorSource(text))


```

```{r message=FALSE, warning=FALSE}

toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
TextDoc <- tm_map(TextDoc, toSpace, "/")
TextDoc <- tm_map(TextDoc, toSpace, "@")
TextDoc <- tm_map(TextDoc, toSpace, "\\|")


```


```{r message=FALSE, warning=FALSE}
TextDoc <- tm_map(TextDoc, content_transformer(tolower))
```

```{r message=FALSE, warning=FALSE}
TextDoc <- tm_map(TextDoc, removeNumbers)
```


```{r message=FALSE, warning=FALSE}
TextDoc <- tm_map(TextDoc, removeWords, stopwords("english"))

TextDoc <- tm_map(TextDoc, removeWords, c("s", "company", "team"))

TextDoc <- tm_map(TextDoc, removePunctuation)
TextDoc <- tm_map(TextDoc, stripWhitespace)
TextDoc <- tm_map(TextDoc, stemDocument)

```

```{r message=FALSE, warning=FALSE}
TextDoc_dtm <- TermDocumentMatrix(TextDoc)
dtm_m <- as.matrix(TextDoc_dtm)

```


```{r}
dtm_v <- sort(rowSums(dtm_m),decreasing=TRUE)
dtm_d <- data.frame(word = names(dtm_v),freq=dtm_v)
```


```{r}
head(dtm_d, 5)
```
```{r}
wordcloud(words = dtm_d$word, freq = dtm_d$freq, min.freq = 1, max.words=50,random.order=FALSE, rot.per=0.40, 
          colors=brewer.pal(8, "Dark2"))

```


```{r}
#findAssocs(TextDoc_dtm, terms = c("exam","cbse","cancel"), 
           #corlimit = 0.25)
#findAssocs(TextDoc_dtm, terms = findFreqTerms(TextDoc_dtm, 
            #                                  lowfreq = 6), 
           #corlimit = 0.25)
```
```{r}
syuzhet_vector <- get_sentiment(text, method="syuzhet")
head(syuzhet_vector)
summary(syuzhet_vector)

```

```{r}
bing_vector <- get_sentiment(text, method="bing")
head(bing_vector)

```


```{r}
afinn_vector <- get_sentiment(text, method="afinn")
head(afinn_vector)
summary(afinn_vector)
```

## Including Plots

You can also embed plots, for example:

```{r}
d<-get_nrc_sentiment(text)
head (d,10)

td<-data.frame(t(d))
```
```{r}
barplot(
  sort(colSums(prop.table(d))), 
  horiz = TRUE, 
  cex.names = 0.7, 
  las = 1, 
  main = "Emotions in Text", xlab="Percentage"
)

```


